### ISSUE TITLE
Edison crashes on startup if it can't find the mothership

### ISSUE THREAD

**Issue by thatandromeda** [MeasureTheFuture/scout#1]
_What I did_

Installed scout on Edison per installation instructions; did _not_ start up a mothership anywhere; ran `./scout`.

_What I expected_

Either a running scout (ideally with some sort of feedback telling me it was running); a prompt for missing configuration info; or some sort of graceful exit with an informative error message.

_What I saw_

Immediate exit with the error message

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8069865]

goroutine 1 [running]:
main.post(0x869e960, 0x9, 0x977b41e0, 0x4d, 0x86561418, 0x977f4330)
        /home/root/mtf/src/scout/controller.go:139 +0x3c5
main.postLog(0x0, 0x40cb5800, 0xa, 0x80, 0x5, 0x1f4, 0x0, 0x403e0000, 0x1, 0x977acdb0, ...)
        /home/root/mtf/src/scout/heartbeat.go:107 +0x1a3
main.main()
        /home/root/mtf/src/scout/main.go:66 +0x557

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1662 +0x1
```

I have a core dump but it's too big for GitHub to attach - tell me if you still need it and I'll figure out how to get it to you.

**Comment by cfreeman** [comment]
Thanks for the extra details. I found something, but it was introduced after your initial installation attempt (when I pushed the scout ID into the HTTP headers). So this commit may not have fixed the issue. 

Are you able to give me the steps I need to perform in taking a working install back to this broken state? I'm still struggling to reproduce it. You can also try pulling the latest version and see if it is fixed for you.

**Comment by cfreeman** [comment]
Unable to reproduce, and the new installer -- https://github.com/MeasureTheFuture/installer makes everything a bit easier to configure.
