### ISSUE TITLE
Timed measurement/Scheduling

### ISSUE THREAD

**Issue by griffey** [MeasureTheFuture/scout#2]
Spaces with MtF sensors are typically not going to be 24/7 spaces, and one possible solution for tons of dead data/useless DB entries would be to enable a cron or other timed scout actions that enable measurement at open and disable it at close.

**Comment by cfreeman** [comment]
Shifted this issue to the mothership -- https://github.com/MeasureTheFuture/mothership/issues/5 . Logic will be better implemented there, closer to the UI.
